using Microsoft.UI.Xaml;
using Samt.Core.Domain;
using Samt.Core.Formatting;

namespace Samt_App.Services;

/// <summary>
/// App strings for ar / en-US / fr / es.
/// Does not require ApplicationLanguages.PrimaryLanguageOverride (throws on many unpackaged WinUI runs).
/// </summary>
public sealed partial class LocalizationService
{
    public string CurrentLanguage { get; private set; } = "ar";

    public event EventHandler? LanguageChanged;

    public bool IsArabic =>
        CurrentLanguage.StartsWith("ar", StringComparison.OrdinalIgnoreCase);

    /// <summary>True when layout should be RTL (Arabic). French/Spanish/English are LTR.</summary>
    public bool IsRightToLeft => IsArabic;

    public void Initialize(string? language = null)
    {
        ApplyLanguage(language ?? CurrentLanguage, raiseEvent: false);
    }

    public void SetLanguage(string language)
    {
        var normalized = Normalize(language);
        if (string.Equals(CurrentLanguage, normalized, StringComparison.OrdinalIgnoreCase))
        {
            LatinDigits.ApplyProcessDefaults(normalized);
            return;
        }

        ApplyLanguage(normalized, raiseEvent: true);
    }

    public string Get(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return key ?? string.Empty;
        }

        var map = MapFor(CurrentLanguage);
        if (map.TryGetValue(key, out var value))
        {
            return LatinDigits.EnsureLatin(value);
        }

        // Fallback to English so incomplete catalogs still show usable UI.
        if (!ReferenceEquals(map, English) && English.TryGetValue(key, out var english))
        {
            return LatinDigits.EnsureLatin(english);
        }

        return key;
    }

    public string GetPrayerName(PrayerEvent prayer)
        => Get($"Prayer.{prayer}");

    public FlowDirection FlowDirection =>
        IsRightToLeft ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

    private void ApplyLanguage(string language, bool raiseEvent)
    {
        CurrentLanguage = Normalize(language);
        LatinDigits.ApplyProcessDefaults(CurrentLanguage);

        // Optional: try system override when available (packaged). Never fail launch if it throws.
        try
        {
            Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = CurrentLanguage;
        }
        catch
        {
            // Unpackaged WinUI often throws InvalidOperationException here — ignore.
        }

        if (raiseEvent)
        {
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <summary>Normalizes to ar | en-US | fr | es.</summary>
    public static string Normalize(string language)
    {
        if (string.IsNullOrWhiteSpace(language))
        {
            return "ar";
        }

        var t = language.Trim();
        if (t.StartsWith("ar", StringComparison.OrdinalIgnoreCase))
        {
            return "ar";
        }

        if (t.StartsWith("fr", StringComparison.OrdinalIgnoreCase))
        {
            return "fr";
        }

        if (t.StartsWith("es", StringComparison.OrdinalIgnoreCase))
        {
            return "es";
        }

        if (t.StartsWith("en", StringComparison.OrdinalIgnoreCase))
        {
            return "en-US";
        }

        return "ar";
    }

    private static Dictionary<string, string> MapFor(string language)
        => language switch
        {
            "fr" => French,
            "es" => Spanish,
            "en-US" => English,
            _ => Arabic
        };

    private static readonly Dictionary<string, string> Arabic = new(StringComparer.Ordinal)
    {
        ["AppDisplayName"] = "سَمت",
        ["AppTagline"] = "مواقيت الأذان",
        ["NavToday"] = "اليوم",
        ["NavLocations"] = "المواقع",
        ["NavAlerts"] = "التنبيهات",
        ["NavAdhkar"] = "مكتبة الأذكار",
        ["AdhkarLibraryTitle"] = "مكتبة الأذكار",

        ["NavDiagnostics"] = "التشخيص",
        ["NavDesignLab"] = "مختبر التصميم",
        ["NavSettings"] = "الإعدادات",
        ["Language"] = "اللغة",
        ["Theme"] = "المظهر",
        ["ThemeSystem"] = "تلقائي",
        ["ThemeLight"] = "فاتح",
        ["ThemeDark"] = "داكن",
        ["ThemeRamadan"] = "رمضان",
        ["ThemeAlgeria"] = "الجزائر",
        ["ThemeMorocco"] = "المغرب",
        ["Location"] = "الموقع",
        ["Method"] = "طريقة الحساب",
        ["Date"] = "التاريخ",
        ["Recalculate"] = "إعادة الحساب",
        ["Latitude"] = "خط العرض",
        ["Longitude"] = "خط الطول",
        ["TimeZone"] = "المنطقة الزمنية",
        ["Inputs"] = "المدخلات",
        ["Results"] = "مواقيت الأذان اليوم",
        ["Disclaimer"] = "هذه تقديرات فلكية محلية وليست مصدراً رسمياً. تحقق من جدول مسجدك. الأرقام تُعرض بالأرقام اللاتينية (0-9).",
        ["Prayer.Imsak"] = "الإمساك",
        ["Prayer.Fajr"] = "الفجر",
        ["Prayer.Sunrise"] = "الشروق",
        ["Prayer.Dhuhr"] = "الظهر",
        ["Prayer.Asr"] = "العصر",
        ["Prayer.Maghrib"] = "المغرب",
        ["Prayer.Isha"] = "العشاء",
        ["Prayer.Midnight"] = "منتصف الليل",
        ["Prayer.Jumuah"] = "الجمعة",
        ["AsrMadhab"] = "مذهب العصر",
        ["AsrStandard"] = "الجمهور",
        ["AsrHanafi"] = "الحنفي",
        ["AdhanTime"] = "موعد الأذان",
        ["NextPrayer"] = "الأذان التالي",
        ["NextAdhan"] = "الأذان التالي",
        ["DayComplete"] = "انتهت مواقيت الأذان اليوم",
        ["CalcStatusFormat"] = "{0} · {1}",
        ["SavedLocations"] = "المواقع المحفوظة",
        ["LocationEditor"] = "تحرير الموقع",
        ["LocationName"] = "الاسم",
        ["UseLocation"] = "تفعيل",
        ["NewLocation"] = "جديد",
        ["DeleteLocation"] = "حذف",
        ["SaveLocation"] = "حفظ",
        ["UseGps"] = "تحديد موقعي",
        ["LocationPrivacyNote"] = "الموقع يبقى على جهازك فقط. يمكنك رفض الإذن وإدخال الإحداثيات يدوياً.",
        ["SelectLocationFirst"] = "اختر موقعاً أولاً.",
        ["LocationActivated"] = "تم تفعيل الموقع.",
        ["NameRequired"] = "الاسم مطلوب.",
        ["InvalidTimeZone"] = "المنطقة الزمنية غير صالحة.",
        ["LocationSaved"] = "تم حفظ الموقع.",
        ["CannotDeleteLastLocation"] = "لا يمكن حذف آخر موقع.",
        ["LocationDeleted"] = "تم حذف الموقع.",
        ["EnterCoordinatesHint"] = "أدخل الاسم والإحداثيات ثم احفظ.",
        ["RequestingLocation"] = "جاري طلب إذن الموقع…",
        ["LocationDenied"] = "رُفض إذن الموقع. استخدم الإدخال اليدوي.",
        ["LocationFailed"] = "تعذر الحصول على الموقع.",
        ["LocationFromGps"] = "تم الحفظ من GPS وتفعيله.",
        ["GpsLocationName"] = "موقعي (GPS)",
        ["InvalidLatitude"] = "خط العرض غير صالح (−90 إلى 90).",
        ["InvalidLongitude"] = "خط الطول غير صالح (−180 إلى 180).",
        ["InvalidFridayTime"] = "وقت الجمعة غير صالح. استخدم HH:mm (مثل 13:30).",
        ["FridaySection"] = "الجمعة",
        ["FridayTimeMode"] = "وقت الجمعة",
        ["FridayFollowDhuhr"] = "يتبع الظهر المحسوب",
        ["FridayFixedTime"] = "وقت ثابت",
        ["FixedFridayTime"] = "الوقت الثابت (محلي)",
        ["SuppressDhuhrOnFriday"] = "تعطيل تنبيه الظهر يوم الجمعة (الجمعة بدلًا منه)",
        ["AlertsStartSection"] = "موعد الأذان",
        ["AlertsBeforeSection"] = "تنبيه مسبق",
        ["AlertsStartEnabled"] = "تفعيل تنبيه موعد الأذان",
        ["AlertsBeforeEnabled"] = "تفعيل التنبيه المسبق",
        ["AlertsGeneralOffset"] = "الدقائق العامة قبل الأذان",
        ["AlertsChannels"] = "القنوات",
        ["ChannelToast"] = "إشعار Windows",
        ["ChannelOverlay"] = "نافذة عائمة",
        ["ChannelAudio"] = "صوت / أذان",
        ["ChannelAudioCue"] = "صوت",
        ["BeforeAudioHint"] = "عند التفعيل يُشغَّل صوت التنبيه المسبق المختار من مكتبة الأصوات أدناه.",
        ["ManualTimeBadge"] = "يدوي",
        ["EditPrayerTime"] = "تعديل موعد الأذان",
        ["ResetPrayerTime"] = "إعادة الحساب",
        ["PrayerTimeSaved"] = "تم حفظ التعديل اليدوي.",
        ["InvalidPrayerTime"] = "أدخل وقتًا بصيغة HH:mm (مثل 05:30).",
        ["AlertsStartPrayers"] = "أوقات الأذان",
        ["AlertsExceptions"] = "استثناءات لكل أذان (دقائق)",
        ["AlertsExceptionsHint"] = "اترك الحقل فارغًا لاستخدام القاعدة العامة. قيمة مختلفة تتقدم على العامة. إلغاء التحديد يلغي التنبيه المسبق لذلك الأذان.",
        ["AlertsPriorityNote"] = "الأولوية: الاستثناء الخاص بالصلاة يتقدم على القاعدة العامة. عند التعارض يبقى تنبيه واحد لكل أذان.",
        ["AlertsFridayHint"] = "وقت الجمعة وتعطيل الظهر يُضبطان في صفحة المواقع لكل موقع.",
        ["SaveAlerts"] = "حفظ التنبيهات",
        ["AlertsSaved"] = "تم حفظ قواعد التنبيه.",
        ["InvalidOffsetMinutes"] = "أدخل دقائق صحيحة بين 0 و 180.",
        ["OverlayPrayerEntered"] = "حان موعد الأذان",
        ["OverlayAdhanArrived"] = "حان موعد الأذان",
        ["OverlayPreAlertFormat"] = "بعد {0} دقيقة",
        ["OverlayStopAdhan"] = "إيقاف الأذان",
        ["OverlayDismiss"] = "إخفاء",
        ["OverlayMute"] = "كتم الصوت",
        ["OverlayUnmute"] = "إلغاء الكتم",
        ["OverlayClose"] = "إغلاق",
        ["Qibla"] = "القبلة",
        ["QiblaBearingFormat"] = "{0}° · {1}",
        ["QiblaKm"] = "كم",
        ["QiblaAtKaaba"] = "عند الكعبة",
        ["RamadanBadge"] = "رمضان",
        ["Prayer.MaghribIftar"] = "المغرب (الإفطار)",
        ["HijriDayOffset"] = "إزاحة اليوم الهجري",
        ["HijriDayOffsetHint"] = "من −3 إلى 3 لضبط الرؤية المحلية",
        ["Hijri.Month.1"] = "محرم",
        ["Hijri.Month.2"] = "صفر",
        ["Hijri.Month.3"] = "ربيع الأول",
        ["Hijri.Month.4"] = "ربيع الآخر",
        ["Hijri.Month.5"] = "جمادى الأولى",
        ["Hijri.Month.6"] = "جمادى الآخرة",
        ["Hijri.Month.7"] = "رجب",
        ["Hijri.Month.8"] = "شعبان",
        ["Hijri.Month.9"] = "رمضان",
        ["Hijri.Month.10"] = "شوال",
        ["Hijri.Month.11"] = "ذو القعدة",
        ["Hijri.Month.12"] = "ذو الحجة",
        ["Compass.N"] = "ش",
        ["Compass.NE"] = "ش ر",
        ["Compass.E"] = "ر",
        ["Compass.SE"] = "ج ر",
        ["Compass.S"] = "ج",
        ["Compass.SW"] = "ج غ",
        ["Compass.W"] = "غ",
        ["Compass.NW"] = "ش غ",
        ["AdhkarSubtitle"] = "مكتبة أذكار أوفلاين منظّمة حسب الأقسام — مع عدّاد وتتبع تقدّم في نافذة القراءة.",
        ["AdhkarDisclaimer"] = "محتوى تذكيري أوفلاين مستوحى في تنظيمه من azkar.me (حصن المسلم). ليس مصدراً للفتوى — راجع طبعة موثوقة للنص الكامل. الأرقام لاتينية 0–9.",
        ["Adhkar.Source.AzkarMe"] = "المصدر: azkar.me / حصن المسلم (تنظيم)",
        ["Adhkar.Group.Daily"] = "اليومية",
        ["Adhkar.Group.Prayer"] = "الصلاة والمسجد",
        ["Adhkar.Group.Life"] = "مواقف الحياة",
        ["Adhkar.Group.Praise"] = "التسبيح والأدعية",
        ["Adhkar.WakeUp"] = "أذكار الاستيقاظ",
        ["Adhkar.Tasbeeh"] = "التسبيح",
        ["Adhkar.Istighfar"] = "الاستغفار",
        ["Adhkar.Salawat"] = "الصلاة على النبي",
        ["Adhkar.GeneralDuas"] = "أدعية عامة",
        ["Adhkar.Home"] = "أذكار المنزل",
        ["Adhkar.Adhan"] = "أذكار الأذان",
        ["Adhkar.Mosque"] = "أذكار المسجد",
        ["Adhkar.Travel"] = "أذكار السفر",
        ["Adhkar.Food"] = "أذكار الطعام",
        ["Adhkar.Clothing"] = "أذكار اللباس",
        ["Adhkar.Sickness"] = "أذكار المريض والرقية",
        ["Adhkar.Distress"] = "أدعية الهمّ والحزن",
        ["Adhkar.Misc"] = "أذكار متفرقة",
        ["Adhkar.Prayer"] = "أذكار الصلاة",
        ["Adhkar.QuranDuas"] = "أدعية من القرآن",
        ["Adhkar.SunnahDuas"] = "أدعية من السنة",
        ["AdhkarItemCountFormat"] = "{0} ذكر",
        ["AdhkarMarkDone"] = "تمّ",
        ["AdhkarCount"] = "عدّ",
        ["AdhkarTapToCount"] = "اضغط على البطاقة أو «عدّ» لتسجيل القراءة",
        ["AdhkarResetProgress"] = "إعادة تعيين التقدّم",
        ["AdhkarSetProgressFormat"] = "مكتمل: {0}/{1} · تكرارات: {2}/{3}",

        ["Adhkar.AfterPrayer"] = "بعد الصلاة",
        ["Adhkar.AfterPrayer.1.Arabic"] = "أَسْتَغْفِرُ اللَّهَ (ثلاثًا)",
        ["Adhkar.AfterPrayer.1.Translation"] = "أستغفر الله (ثلاث مرات)",
        ["Adhkar.AfterPrayer.2.Arabic"] = "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
        ["Adhkar.AfterPrayer.2.Translation"] = "اللهم أنت السلام ومنك السلام، تباركت يا ذا الجلال والإكرام",
        ["Adhkar.AfterPrayer.3.Arabic"] = "سُبْحَانَ اللَّهِ · الْحَمْدُ لِلَّهِ · اللَّهُ أَكْبَرُ",
        ["Adhkar.AfterPrayer.3.Translation"] = "سبحان الله · الحمد لله · الله أكبر",
        ["Adhkar.Morning"] = "أذكار الصباح",
        ["Adhkar.Morning.1.Arabic"] = "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
        ["Adhkar.Morning.1.Translation"] = "أصبحنا وأصبح الملك لله، والحمد لله",
        ["Adhkar.Morning.2.Arabic"] = "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
        ["Adhkar.Morning.2.Translation"] = "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم",
        ["Adhkar.Evening"] = "أذكار المساء",
        ["Adhkar.Evening.1.Arabic"] = "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
        ["Adhkar.Evening.1.Translation"] = "أمسينا وأمسى الملك لله، والحمد لله",
        ["Adhkar.Evening.2.Arabic"] = "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        ["Adhkar.Evening.2.Translation"] = "أعوذ بكلمات الله التامات من شر ما خلق",
        ["AppOptions"] = "خيارات التطبيق",
        ["AutoStartEnabled"] = "بدء التشغيل مع Windows",
        ["ShowMissedAlertOnResume"] = "تنبيه عند فوات تنبيه (استئناف / تشغيل متأخر)",
        ["ToggleOn"] = "تشغيل",
        ["ToggleOff"] = "إيقاف",
        ["RefreshProcessStatus"] = "تحديث حالة العملية",
        ["ProcessStatusFormat"] = "الذاكرة العاملة: {0} ميغابايت · أحداث مجدولة متبقية: {1} · بدء التشغيل: {2}",
        ["AutoStartRegisteredYes"] = "مسجّل",
        ["AutoStartRegisteredNo"] = "غير مسجّل",
        ["MissedAlertTitle"] = "فات تنبيه أذان",
        ["MissedAlertBodyOne"] = "فات تنبيه {0} ({1}). لا يُعاد تشغيل الأذان المتأخر.",
        ["MissedAlertBodyMany"] = "فاتت {0} تنبيهات: {1}. لا يُعاد تشغيل الأذان المتأخر.",
        ["SoundLibrary"] = "مكتبة الأصوات",
        ["SoundLibraryHint"] = "اختر أذان موعد الأذان، وصوت التنبيه المسبق (تكبير / حي على الصلاة / نغمة). يمكنك إضافة ملفاتك.",
        ["AdhanSound"] = "صوت الأذان (موعد الأذان)",
        ["PreAlertSound"] = "صوت التنبيه المسبق",
        ["PreviewSound"] = "استماع",
        ["AddSound"] = "إضافة صوت…",
        ["StopSound"] = "إيقاف",
        ["SoundLibraryNote"] = "عينات الأذان من PrayTimes.org للاستخدام الشخصي. عبارات التكبير وحي على الصلاة نغمات قصيرة قابلة للاستبدال. تحقق من الترخيص قبل أي نشر عام.",
        ["SoundAdded"] = "أُضيف الصوت إلى المكتبة.",
        ["SoundAddFailed"] = "تعذّر إضافة الصوت:",
        ["PhaseBanner"] = "المرحلة 0–9: الهيكل حتى التقويم الهجري والأيام الخاصة",
        ["NavCalendar"] = "التقويم",
        ["CalendarDisclaimer"] = "تقويم هجري جدولي مع إزاحة اختيارية — ليس رؤية هلال رسمية ولا فتوى.",
        ["CalendarToday"] = "اليوم",
        ["CalendarPrevMonth"] = "الشهر السابق",
        ["CalendarNextMonth"] = "الشهر التالي",
        ["CalendarDaySheetTitle"] = "اليوم",
        ["CalendarClose"] = "إغلاق",
        ["CalendarMuteReminder"] = "كتم تذكير هذا اليوم",
        ["CalendarMuteHint"] = "وقت التذكير يُضبط من الإعدادات. التمييز على الشبكة يبقى ظاهراً.",
        ["CalendarOrdinaryDay"] = "يوم عادي — لا مناسبة خاصة.",
        ["SettingsCalendarSection"] = "التقويم والهجري",
        ["SettingsCalendarCountry"] = "بلد التقويم (العطل المدنية)",
        ["SettingsCalendarCountryDefault"] = "حسب الموقع النشط",
        ["SettingsCalendarCountryAlgeria"] = "الجزائر",
        ["SpecialDayRemindersMaster"] = "تفعيل تذكير الأيام الخاصة",
        ["SpecialDayIslamicSet"] = "المناسبات الإسلامية",
        ["SpecialDayCountrySet"] = "عطل بلد التقويم",
        ["SpecialDayReminderTime"] = "وقت التذكير (صباحاً)",
        ["SpecialDayAlertTitle"] = "يوم خاص",
        ["SpecialDayAlertBody"] = "{0} — {1}",
        ["SpecialDayMissedTitle"] = "تذكير يوم خاص فائت",
        ["SpecialDayMissedBodyOne"] = "فات تذكير {0} ({1}).",
        ["SpecialDayMissedBodyMany"] = "فاتت {0} تذكيرات: {1}.",
        ["SpecialDay.CommonlyObservedHint"] = "يُذكر كثيراً في التقويم الثقافي — ليس فتوى.",
        ["HijriDayOffsetDiagnosticsHint"] = "للقراءة فقط — غيّر الإزاحة من الإعدادات ← التقويم.",
        ["LocationCountryCode"] = "رمز البلد (اختياري، مثل DZ)",
        ["Weekday.Short.0"] = "أحد",
        ["Weekday.Short.1"] = "إثن",
        ["Weekday.Short.2"] = "ثلا",
        ["Weekday.Short.3"] = "أرب",
        ["Weekday.Short.4"] = "خمي",
        ["Weekday.Short.5"] = "جمع",
        ["Weekday.Short.6"] = "سبت",
        ["SpecialDay.islamic.new_year"] = "رأس السنة الهجرية",
        ["SpecialDay.islamic.ashura"] = "عاشوراء",
        ["SpecialDay.islamic.mawlid"] = "المولد النبوي",
        ["SpecialDay.islamic.isra_miraj"] = "الإسراء والمعراج",
        ["SpecialDay.islamic.mid_shaban"] = "منتصف شعبان",
        ["SpecialDay.islamic.ramadan_start"] = "بداية رمضان",
        ["SpecialDay.islamic.laylat_al_qadr_marker"] = "علامة ليلة القدر (٢٧)",
        ["SpecialDay.islamic.eid_fitr"] = "عيد الفطر",
        ["SpecialDay.islamic.arafah"] = "يوم عرفة",
        ["SpecialDay.islamic.eid_adha"] = "عيد الأضحى",
        ["SpecialDay.islamic.tashreeq_11"] = "أيام التشريق (١١)",
        ["SpecialDay.islamic.tashreeq_12"] = "أيام التشريق (١٢)",
        ["SpecialDay.islamic.tashreeq_13"] = "أيام التشريق (١٣)",
        ["SpecialDay.dz.new_year"] = "رأس السنة الميلادية",
        ["SpecialDay.dz.yennayer"] = "ينّاير",
        ["SpecialDay.dz.labour"] = "عيد العمال",
        ["SpecialDay.dz.independence"] = "عيد الاستقلال",
        ["SpecialDay.dz.revolution"] = "عيد الثورة",
        ["CalendarShowGregorian"] = "ميلادي",
        ["CalendarShowHijri"] = "هجري",
        ["CalendarToggleMode"] = "تبديل نوع التقويم",
        ["CalendarAddReminder"] = "إضافة تذكير",
        ["CalendarSaveReminder"] = "حفظ التذكير",
        ["CalendarUserReminders"] = "تذكيراتك",
        ["CalendarReminderTitle"] = "العنوان",
        ["CalendarReminderNote"] = "ملاحظة (اختياري)",
        ["CalendarReminderRepeatCount"] = "عدد التكرار",
        ["CalendarReminderInterval"] = "الفاصل بين التكرار (دقائق)",
        ["CalendarReminderDelivery"] = "طريقة تنبيه تقويم / تذكيرات الأيام",
        ["CalendarDeliveryToast"] = "إشعار Windows",
        ["CalendarDeliverySound"] = "صوت",
        ["CalendarDeliverySilentWindow"] = "نافذة صامتة",
        ["CalendarDeliveryHint"] = "ينطبق على الأيام الخاصة وتذكيراتك المخصصة. يمكن الجمع بين أكثر من خيار.",
        ["ExitApp"] = "خروج من التطبيق",
        ["TrayOpen"] = "فتح",
        ["TrayExit"] = "خروج",
        ["SettingsLanguageSection"] = "لغة العرض",
        ["SettingsThemeSection"] = "المظهر",
        ["SettingsAboutSection"] = "حول",
        ["SettingsCommunitySection"] = "روابط رسمية",
        ["SettingsUpdatesSection"] = "التحديثات",
        ["SettingsAdhkarSection"] = "تذكير الأذكار",
        ["SettingsAppearanceSection"] = "الشفافية والمظهر",
        ["SettingsAppearanceHint"] = "شفافية نوافذ التطبيق الرئيسية وقارئ الأذكار (30–100٪). نافذة الأذان لها شفافية مستقلة.",
        ["SettingsWindowOpacity"] = "شفافية النوافذ",
        ["AdhkarAutoAdvance"] = "الانتقال تلقائياً للذكر التالي عند الإكمال",
        ["WizardTitle"] = "الإعداد الأولي",
        ["WizardSkip"] = "تخطّي الإعداد",
        ["WizardBack"] = "رجوع",
        ["WizardNext"] = "التالي",
        ["WizardFinish"] = "إنهاء",
        ["WizardStep1Title"] = "الموقع",
        ["WizardStep1Hint"] = "اختر موقعك لحساب مواقيت الصلاة. يمكنك التعديل لاحقاً من صفحة المواقع.",
        ["WizardUseGps"] = "تحديد موقعي",
        ["WizardSearchPlace"] = "البحث عن مكان",
        ["WizardUseSeed"] = "استخدام مدينة افتراضية",
        ["WizardLocationStatus"] = "الموقع النشط",
        ["WizardStep2Title"] = "مواقيت الصلاة",
        ["WizardStep2Hint"] = "راجع الطريقة والمذهب. الأوقات تُحسب محلياً من إحداثياتك.",
        ["WizardCalcMethod"] = "طريقة الحساب",
        ["WizardAsrMadhab"] = "مذهب العصر",
        ["WizardStep3Title"] = "جدول الأذكار",
        ["WizardStep3Hint"] = "فعّل التذكير واضبط الأوقات الافتراضية. يمكن تغييرها من الإعدادات.",
        ["WizardStep4Title"] = "نظرة سريعة",
        ["WizardStep4Hint"] = "أهم ما تحتاج معرفته للبدء.",
        ["WizardTourTray"] = "إغلاق النافذة يخفي التطبيق إلى شريط المهام؛ الخروج من القائمة أو زر الخروج.",
        ["WizardTourToday"] = "اليوم يعرض العدّ التنازلي للصلاة التالية ومواقيت اليوم.",
        ["WizardTourAlerts"] = "التنبيهات: إشعار Windows، نافذة الأذان، والصوت.",
        ["WizardTourAdhkar"] = "الأذكار أوفلاين مع قارئ وعدّاد؛ يمكن التذكير في الصباح والمساء وبعد الصلاة والنوم.",
        ["WizardWelcome"] = "مرحباً بك في سَمت",
        ["OpenGitHub"] = "GitHub",
        ["PublisherLabel"] = "الناشر",
        ["VersionLabel"] = "الإصدار",
        ["CheckForUpdates"] = "البحث عن تحديثات",
        ["AutoCheckUpdates"] = "البحث تلقائياً عن التحديثات",
        ["PlaceSearch"] = "البحث عن مكان",
        ["PlaceSearchHint"] = "البحث بالاسم (يتطلب إنترنت). يمكنك تعديل الإحداثيات يدوياً.",
        ["PlaceSearchNoResults"] = "لا نتائج.",
        ["PlaceSearchFailed"] = "تعذّر البحث. تحقق من الشبكة أو أدخل الإحداثيات.",
        ["PlaceSearchAttribution"] = "بحث الأماكن عبر بيانات مفتوحة (OpenStreetMap Nominatim).",
        ["ApplyPlaceResult"] = "استخدام هذا المكان",
        ["UpdateCheckFailed"] = "تعذّر التحقق من التحديثات.",
        ["UpdateUpToDate"] = "أنت على أحدث إصدار ({0}).",
        ["UpdateAvailableFormat"] = "يتوفر إصدار جديد {0} (الحالي {1}).",
        ["UpdateHashMismatch"] = "فشل التحقق من سلامة ملف التحديث (SHA-256).",
        ["UpdateDownloadPrompt"] = "هل تريد تنزيل المثبّت وتشغيله؟",
        ["UpdateDownloading"] = "جاري تنزيل التحديث…",
        ["Adhkar.Sleep"] = "أذكار النوم",
        ["AdhkarOpenReader"] = "فتح القارئ",
        ["AdhkarPlay"] = "تشغيل (قريباً)",
        ["AdhkarPrev"] = "السابق",
        ["AdhkarNext"] = "التالي",
        ["AdhkarProgressFormat"] = "{0} / {1}",
        ["AdhkarRemindersMaster"] = "تفعيل تذكير الأذكار",
        ["AdhkarMorningToggle"] = "أذكار الصباح",
        ["AdhkarEveningToggle"] = "أذكار المساء",
        ["AdhkarAfterPrayerToggle"] = "أذكار بعد الصلاة",
        ["AdhkarSleepToggle"] = "أذكار النوم",
        ["AdhkarSettingsHint"] = "فعّل كل نوع واضبط وقت العرض الافتراضي. أذكار بعد الصلاة تُعرض بعد كل أذان مع تأخير اختياري بالدقائق.",
        ["AdhkarDefaultTime"] = "الوقت",
        ["AdhkarAfterPrayerDelay"] = "بعد الأذان بـ",
        ["AdhkarAfterPrayerHint"] = "بعد كل صلاة: تظهر أذكار بعد الصلاة فور انتهاء الأذان (أو بعد التأخير المحدد). القيمة 0 = مباشرة بعد الأذان / إغلاق نافذة الأذان.",
        ["AdhkarMinutesUnit"] = "دقيقة",

        ["Adhkar.Morning.3.Translation"] = "رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً",
        ["Adhkar.Morning.4.Translation"] = "اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور",
        ["Adhkar.Morning.5.Translation"] = "سبحان الله وبحمده",
        ["Adhkar.Evening.3.Translation"] = "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم",
        ["Adhkar.Evening.4.Translation"] = "اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك المصير",
        ["Adhkar.Evening.5.Translation"] = "أعوذ بكلمات الله التامات من غضبه وعقابه وشر عباده ومن همزات الشياطين وأن يحضرون",
        ["Adhkar.AfterPrayer.3a.Translation"] = "سبحان الله",
        ["Adhkar.AfterPrayer.3b.Translation"] = "الحمد لله",
        ["Adhkar.AfterPrayer.3c.Translation"] = "الله أكبر",
        ["Adhkar.AfterPrayer.4.Translation"] = "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد، وهو على كل شيء قدير",
        ["Adhkar.Sleep.1.Translation"] = "باسمك اللهم أموت وأحيا",
        ["Adhkar.Sleep.2.Translation"] = "اللهم قني عذابك يوم تبعث عبادك",
        ["Adhkar.Sleep.3.Translation"] = "باسمك ربي وضعت جنبي وبك أرفعه…",
        ["Adhkar.Sleep.4.Translation"] = "آمن الرسول بما أنزل إليه من ربه والمؤمنون (آية الكرسي / خواتيم البقرة — راجع مصدراً موثوقاً للنص الكامل)",
        ["Adhkar.Sleep.5.Translation"] = "اللهم أسلمت نفسي إليك وفوضت أمري إليك…",
    };

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["AppDisplayName"] = "SAMT",
        ["AppTagline"] = "Adhan times",
        ["NavToday"] = "Today",
        ["NavLocations"] = "Locations",
        ["NavAlerts"] = "Alerts",
        ["NavAdhkar"] = "Adhkar library",
        ["AdhkarLibraryTitle"] = "Adhkar library",

        ["NavDiagnostics"] = "Diagnostics",
        ["NavDesignLab"] = "Design lab",
        ["NavSettings"] = "Settings",
        ["Language"] = "Language",
        ["Theme"] = "Theme",
        ["ThemeSystem"] = "System",
        ["ThemeLight"] = "Light",
        ["ThemeDark"] = "Dark",
        ["ThemeRamadan"] = "Ramadan",
        ["ThemeAlgeria"] = "Algeria",
        ["ThemeMorocco"] = "Morocco",
        ["Location"] = "Location",
        ["Method"] = "Calculation method",
        ["Date"] = "Date",
        ["Recalculate"] = "Recalculate",
        ["Latitude"] = "Latitude",
        ["Longitude"] = "Longitude",
        ["TimeZone"] = "Time zone",
        ["Inputs"] = "Inputs",
        ["Results"] = "Today's Adhan times",
        ["Disclaimer"] = "Local astronomical estimates — not an official source. Verify against your mosque. Numbers use Latin digits (0-9).",
        ["Prayer.Imsak"] = "Imsak",
        ["Prayer.Fajr"] = "Fajr",
        ["Prayer.Sunrise"] = "Sunrise",
        ["Prayer.Dhuhr"] = "Dhuhr",
        ["Prayer.Asr"] = "Asr",
        ["Prayer.Maghrib"] = "Maghrib",
        ["Prayer.Isha"] = "Isha",
        ["Prayer.Midnight"] = "Midnight",
        ["Prayer.Jumuah"] = "Jumu'ah",
        ["AsrMadhab"] = "Asr madhab",
        ["AsrStandard"] = "Standard",
        ["AsrHanafi"] = "Hanafi",
        ["AdhanTime"] = "Adhan time",
        ["NextPrayer"] = "Next Adhan",
        ["NextAdhan"] = "Next Adhan",
        ["DayComplete"] = "Day's Adhan times complete",
        ["CalcStatusFormat"] = "{0} · {1}",
        ["SavedLocations"] = "Saved locations",
        ["LocationEditor"] = "Edit location",
        ["LocationName"] = "Name",
        ["UseLocation"] = "Activate",
        ["NewLocation"] = "New",
        ["DeleteLocation"] = "Delete",
        ["SaveLocation"] = "Save",
        ["UseGps"] = "Use my location",
        ["LocationPrivacyNote"] = "Location stays on this device only. You can deny permission and enter coordinates manually.",
        ["SelectLocationFirst"] = "Select a location first.",
        ["LocationActivated"] = "Location activated.",
        ["NameRequired"] = "Name is required.",
        ["InvalidTimeZone"] = "Invalid time zone.",
        ["LocationSaved"] = "Location saved.",
        ["CannotDeleteLastLocation"] = "Cannot delete the last location.",
        ["LocationDeleted"] = "Location deleted.",
        ["EnterCoordinatesHint"] = "Enter a name and coordinates, then save.",
        ["RequestingLocation"] = "Requesting location permission…",
        ["LocationDenied"] = "Location permission denied. Use manual entry.",
        ["LocationFailed"] = "Could not get location.",
        ["LocationFromGps"] = "Saved and activated from GPS.",
        ["GpsLocationName"] = "My location (GPS)",
        ["InvalidLatitude"] = "Invalid latitude (−90 to 90).",
        ["InvalidLongitude"] = "Invalid longitude (−180 to 180).",
        ["InvalidFridayTime"] = "Invalid Friday time. Use HH:mm (e.g. 13:30).",
        ["FridaySection"] = "Friday",
        ["FridayTimeMode"] = "Jumu'ah time",
        ["FridayFollowDhuhr"] = "Follow calculated Dhuhr",
        ["FridayFixedTime"] = "Fixed local time",
        ["FixedFridayTime"] = "Fixed time (local)",
        ["SuppressDhuhrOnFriday"] = "Suppress Dhuhr alert on Friday (use Jumu'ah instead)",
        ["AlertsStartSection"] = "Adhan time",
        ["AlertsBeforeSection"] = "Pre-alert",
        ["AlertsStartEnabled"] = "Enable Adhan-time alerts",
        ["AlertsBeforeEnabled"] = "Enable pre-alerts",
        ["AlertsGeneralOffset"] = "General minutes before Adhan",
        ["AlertsChannels"] = "Channels",
        ["ChannelToast"] = "Windows toast",
        ["ChannelOverlay"] = "Overlay",
        ["ChannelAudio"] = "Audio / adhan",
        ["ChannelAudioCue"] = "Sound",
        ["BeforeAudioHint"] = "When enabled, plays the pre-alert sound selected in the sound library below.",
        ["ManualTimeBadge"] = "Manual",
        ["EditPrayerTime"] = "Edit Adhan time",
        ["ResetPrayerTime"] = "Reset calculated",
        ["PrayerTimeSaved"] = "Manual adjustment saved.",
        ["InvalidPrayerTime"] = "Enter a time as HH:mm (e.g. 05:30).",
        ["AlertsStartPrayers"] = "Adhan times",
        ["AlertsExceptions"] = "Per-Adhan exceptions (minutes)",
        ["AlertsExceptionsHint"] = "Leave empty to use the general offset. A different value overrides general. Uncheck to cancel pre-alert for that Adhan.",
        ["AlertsPriorityNote"] = "Priority: a per-prayer exception wins over the general rule. Overlaps collapse to one alert per Adhan.",
        ["AlertsFridayHint"] = "Friday time and Dhuhr suppress are set per location on the Locations page.",
        ["SaveAlerts"] = "Save alerts",
        ["AlertsSaved"] = "Notification rules saved.",
        ["InvalidOffsetMinutes"] = "Enter minutes between 0 and 180.",
        ["OverlayPrayerEntered"] = "Adhan time has arrived",
        ["OverlayAdhanArrived"] = "Adhan time has arrived",
        ["OverlayPreAlertFormat"] = "in {0} min",
        ["OverlayStopAdhan"] = "Stop adhan",
        ["OverlayDismiss"] = "Dismiss",
        ["OverlayMute"] = "Mute",
        ["OverlayUnmute"] = "Unmute",
        ["OverlayClose"] = "Close",
        ["Qibla"] = "Qibla",
        ["QiblaBearingFormat"] = "{0}° · {1}",
        ["QiblaKm"] = "km",
        ["QiblaAtKaaba"] = "At the Kaaba",
        ["RamadanBadge"] = "Ramadan",
        ["Prayer.MaghribIftar"] = "Maghrib (Iftar)",
        ["HijriDayOffset"] = "Hijri day offset",
        ["HijriDayOffsetHint"] = "−3 to 3 to match local moon sighting",
        ["Hijri.Month.1"] = "Muharram",
        ["Hijri.Month.2"] = "Safar",
        ["Hijri.Month.3"] = "Rabi' al-Awwal",
        ["Hijri.Month.4"] = "Rabi' al-Thani",
        ["Hijri.Month.5"] = "Jumada al-Ula",
        ["Hijri.Month.6"] = "Jumada al-Akhira",
        ["Hijri.Month.7"] = "Rajab",
        ["Hijri.Month.8"] = "Sha'ban",
        ["Hijri.Month.9"] = "Ramadan",
        ["Hijri.Month.10"] = "Shawwal",
        ["Hijri.Month.11"] = "Dhu al-Qi'dah",
        ["Hijri.Month.12"] = "Dhu al-Hijjah",
        ["Compass.N"] = "N",
        ["Compass.NE"] = "NE",
        ["Compass.E"] = "E",
        ["Compass.SE"] = "SE",
        ["Compass.S"] = "S",
        ["Compass.SW"] = "SW",
        ["Compass.W"] = "W",
        ["Compass.NW"] = "NW",
        ["AdhkarSubtitle"] = "Offline Adhkar library by category — interactive reader with counters and progress.",
        ["AdhkarDisclaimer"] = "Offline reminder content organised after azkar.me (Hisn al-Muslim). Not a fatwa source — verify full wording against a trusted print edition. Latin digits 0–9.",
        ["Adhkar.Source.AzkarMe"] = "Source: azkar.me / Hisn al-Muslim (structure)",
        ["Adhkar.Group.Daily"] = "Daily",
        ["Adhkar.Group.Prayer"] = "Prayer & mosque",
        ["Adhkar.Group.Life"] = "Life situations",
        ["Adhkar.Group.Praise"] = "Praise & duas",
        ["Adhkar.WakeUp"] = "Wake-up Adhkar",
        ["Adhkar.Tasbeeh"] = "Tasbeeh",
        ["Adhkar.Istighfar"] = "Seeking forgiveness",
        ["Adhkar.Salawat"] = "Salawat upon the Prophet",
        ["Adhkar.GeneralDuas"] = "General duas",
        ["Adhkar.Home"] = "Home Adhkar",
        ["Adhkar.Adhan"] = "Adhan Adhkar",
        ["Adhkar.Mosque"] = "Mosque Adhkar",
        ["Adhkar.Travel"] = "Travel Adhkar",
        ["Adhkar.Food"] = "Food Adhkar",
        ["Adhkar.Clothing"] = "Clothing Adhkar",
        ["Adhkar.Sickness"] = "Sickness & ruqyah",
        ["Adhkar.Distress"] = "Distress & anxiety",
        ["Adhkar.Misc"] = "Miscellaneous",
        ["Adhkar.Prayer"] = "Prayer Adhkar",
        ["Adhkar.QuranDuas"] = "Duas from the Quran",
        ["Adhkar.SunnahDuas"] = "Duas from the Sunnah",
        ["AdhkarItemCountFormat"] = "{0} items",
        ["AdhkarMarkDone"] = "Done",
        ["AdhkarCount"] = "Count",
        ["AdhkarTapToCount"] = "Tap the card or Count to register a reading",
        ["AdhkarResetProgress"] = "Reset progress",
        ["AdhkarSetProgressFormat"] = "Done: {0}/{1} · reps: {2}/{3}",

        ["Adhkar.AfterPrayer"] = "After prayer",
        ["Adhkar.AfterPrayer.1.Arabic"] = "أَسْتَغْفِرُ اللَّهَ (ثلاثًا)",
        ["Adhkar.AfterPrayer.1.Translation"] = "I seek forgiveness from Allah (three times)",
        ["Adhkar.AfterPrayer.2.Arabic"] = "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
        ["Adhkar.AfterPrayer.2.Translation"] = "O Allah, You are Peace and from You is peace. Blessed are You, O Owner of majesty and honor.",
        ["Adhkar.AfterPrayer.3.Arabic"] = "سُبْحَانَ اللَّهِ · الْحَمْدُ لِلَّهِ · اللَّهُ أَكْبَرُ",
        ["Adhkar.AfterPrayer.3.Translation"] = "Glory be to Allah · Praise be to Allah · Allah is the Greatest",
        ["Adhkar.Morning"] = "Morning adhkar",
        ["Adhkar.Morning.1.Arabic"] = "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
        ["Adhkar.Morning.1.Translation"] = "We have entered the morning and the dominion belongs to Allah, and all praise is for Allah.",
        ["Adhkar.Morning.2.Arabic"] = "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
        ["Adhkar.Morning.2.Translation"] = "In the name of Allah with whose name nothing on earth or in the heavens can cause harm, and He is the All-Hearing, All-Knowing.",
        ["Adhkar.Evening"] = "Evening adhkar",
        ["Adhkar.Evening.1.Arabic"] = "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
        ["Adhkar.Evening.1.Translation"] = "We have entered the evening and the dominion belongs to Allah, and all praise is for Allah.",
        ["Adhkar.Evening.2.Arabic"] = "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        ["Adhkar.Evening.2.Translation"] = "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        ["AppOptions"] = "App options",
        ["AutoStartEnabled"] = "Start with Windows",
        ["ShowMissedAlertOnResume"] = "Alert when an Adhan notification was missed (resume / late start)",
        ["ToggleOn"] = "On",
        ["ToggleOff"] = "Off",
        ["RefreshProcessStatus"] = "Refresh process status",
        ["ProcessStatusFormat"] = "Working set: {0} MB · remaining planned events: {1} · auto-start: {2}",
        ["AutoStartRegisteredYes"] = "registered",
        ["AutoStartRegisteredNo"] = "not registered",
        ["MissedAlertTitle"] = "Missed Adhan alert",
        ["MissedAlertBodyOne"] = "Missed {0} ({1}). Late adhan is not replayed.",
        ["MissedAlertBodyMany"] = "Missed {0} alerts: {1}. Late adhan is not replayed.",
        ["SoundLibrary"] = "Sound library",
        ["SoundLibraryHint"] = "Choose the Adhan and a pre-alert cue (takbir / hayya 'ala as-salah / soft tone). You can add your own files.",
        ["AdhanSound"] = "Adhan sound (Adhan time)",
        ["PreAlertSound"] = "Pre-alert sound",
        ["PreviewSound"] = "Preview",
        ["AddSound"] = "Add sound…",
        ["StopSound"] = "Stop",
        ["SoundLibraryNote"] = "Adhan samples from PrayTimes.org for personal offline use. Takbir and Hayya cues are short synthetic tones you can replace. Re-verify licensing before any public release.",
        ["SoundAdded"] = "Sound added to the library.",
        ["SoundAddFailed"] = "Could not add sound:",
        ["PhaseBanner"] = "Phase 0–9: shell through Hijri calendar & special days",
        ["NavCalendar"] = "Calendar",
        ["CalendarDisclaimer"] = "Tabular Hijri with optional day offset — not official moon-sighting or a fatwa.",
        ["CalendarToday"] = "Today",
        ["CalendarPrevMonth"] = "Previous month",
        ["CalendarNextMonth"] = "Next month",
        ["CalendarDaySheetTitle"] = "Day",
        ["CalendarClose"] = "Close",
        ["CalendarMuteReminder"] = "Mute reminder for this day",
        ["CalendarMuteHint"] = "Reminder time is set in Settings. Grid highlights still show.",
        ["CalendarOrdinaryDay"] = "Ordinary day — no special observance.",
        ["SettingsCalendarSection"] = "Calendar & Hijri",
        ["SettingsCalendarCountry"] = "Calendar country (civil holidays)",
        ["SettingsCalendarCountryDefault"] = "Follow active location",
        ["SettingsCalendarCountryAlgeria"] = "Algeria",
        ["SpecialDayRemindersMaster"] = "Enable special-day reminders",
        ["SpecialDayIslamicSet"] = "Islamic observances",
        ["SpecialDayCountrySet"] = "Calendar-country holidays",
        ["SpecialDayReminderTime"] = "Reminder time (morning)",
        ["SpecialDayAlertTitle"] = "Special day",
        ["SpecialDayAlertBody"] = "{0} — {1}",
        ["SpecialDayMissedTitle"] = "Missed special-day reminder",
        ["SpecialDayMissedBodyOne"] = "Missed {0} ({1}).",
        ["SpecialDayMissedBodyMany"] = "Missed {0} reminders: {1}.",
        ["SpecialDay.CommonlyObservedHint"] = "Commonly observed culturally — not a fatwa.",
        ["HijriDayOffsetDiagnosticsHint"] = "Read-only here — change the offset under Settings → Calendar.",
        ["LocationCountryCode"] = "Country code (optional, e.g. DZ)",
        ["Weekday.Short.0"] = "Sun",
        ["Weekday.Short.1"] = "Mon",
        ["Weekday.Short.2"] = "Tue",
        ["Weekday.Short.3"] = "Wed",
        ["Weekday.Short.4"] = "Thu",
        ["Weekday.Short.5"] = "Fri",
        ["Weekday.Short.6"] = "Sat",
        ["SpecialDay.islamic.new_year"] = "Islamic New Year",
        ["SpecialDay.islamic.ashura"] = "Ashura",
        ["SpecialDay.islamic.mawlid"] = "Mawlid",
        ["SpecialDay.islamic.isra_miraj"] = "Isra and Mi'raj",
        ["SpecialDay.islamic.mid_shaban"] = "Mid-Sha'ban",
        ["SpecialDay.islamic.ramadan_start"] = "Start of Ramadan",
        ["SpecialDay.islamic.laylat_al_qadr_marker"] = "Laylat al-Qadr marker (27)",
        ["SpecialDay.islamic.eid_fitr"] = "Eid al-Fitr",
        ["SpecialDay.islamic.arafah"] = "Day of 'Arafah",
        ["SpecialDay.islamic.eid_adha"] = "Eid al-Adha",
        ["SpecialDay.islamic.tashreeq_11"] = "Days of Tashreeq (11)",
        ["SpecialDay.islamic.tashreeq_12"] = "Days of Tashreeq (12)",
        ["SpecialDay.islamic.tashreeq_13"] = "Days of Tashreeq (13)",
        ["SpecialDay.dz.new_year"] = "New Year",
        ["SpecialDay.dz.yennayer"] = "Yennayer",
        ["SpecialDay.dz.labour"] = "Labour Day",
        ["SpecialDay.dz.independence"] = "Independence Day",
        ["SpecialDay.dz.revolution"] = "Revolution Day",
        ["CalendarShowGregorian"] = "Gregorian",
        ["CalendarShowHijri"] = "Hijri",
        ["CalendarToggleMode"] = "Switch calendar type",
        ["CalendarAddReminder"] = "Add reminder",
        ["CalendarSaveReminder"] = "Save reminder",
        ["CalendarUserReminders"] = "Your reminders",
        ["CalendarReminderTitle"] = "Title",
        ["CalendarReminderNote"] = "Note (optional)",
        ["CalendarReminderRepeatCount"] = "Repeat count",
        ["CalendarReminderInterval"] = "Minutes between repeats",
        ["CalendarReminderDelivery"] = "Calendar / day-reminder delivery",
        ["CalendarDeliveryToast"] = "Windows notification",
        ["CalendarDeliverySound"] = "Sound",
        ["CalendarDeliverySilentWindow"] = "Silent window",
        ["CalendarDeliveryHint"] = "Applies to special days and your custom reminders. You can combine options.",
        ["ExitApp"] = "Exit app",
        ["TrayOpen"] = "Open",
        ["TrayExit"] = "Exit",
        ["SettingsLanguageSection"] = "Display language",
        ["SettingsThemeSection"] = "Theme",
        ["SettingsAboutSection"] = "About",
        ["SettingsCommunitySection"] = "Official links",
        ["SettingsUpdatesSection"] = "Updates",
        ["SettingsAdhkarSection"] = "Adhkar reminders",
        ["SettingsAppearanceSection"] = "Transparency & appearance",
        ["SettingsAppearanceHint"] = "Opacity for the main window and Adhkar reader (30–100%). The Adhan overlay has its own opacity.",
        ["SettingsWindowOpacity"] = "Window opacity",
        ["AdhkarAutoAdvance"] = "Auto-advance to next Adhkar when complete",
        ["WizardTitle"] = "First-run setup",
        ["WizardSkip"] = "Skip setup",
        ["WizardBack"] = "Back",
        ["WizardNext"] = "Next",
        ["WizardFinish"] = "Finish",
        ["WizardStep1Title"] = "Location",
        ["WizardStep1Hint"] = "Choose your location for prayer times. You can change this later under Locations.",
        ["WizardUseGps"] = "Detect my location",
        ["WizardSearchPlace"] = "Search for a place",
        ["WizardUseSeed"] = "Use a default city",
        ["WizardLocationStatus"] = "Active location",
        ["WizardStep2Title"] = "Prayer times",
        ["WizardStep2Hint"] = "Confirm calculation method and Asr madhab. Times are computed offline from your coordinates.",
        ["WizardCalcMethod"] = "Calculation method",
        ["WizardAsrMadhab"] = "Asr madhab",
        ["WizardStep3Title"] = "Adhkar schedule",
        ["WizardStep3Hint"] = "Optionally enable reminders and set default times. Change anytime in Settings.",
        ["WizardStep4Title"] = "Quick tour",
        ["WizardStep4Hint"] = "What you need to know to get started.",
        ["WizardTourTray"] = "Closing the window hides SAMT to the tray; exit from the pane or tray menu.",
        ["WizardTourToday"] = "Today shows the next-prayer countdown and the day's times.",
        ["WizardTourAlerts"] = "Alerts: Windows toast, Adhan overlay, and audio.",
        ["WizardTourAdhkar"] = "Offline Adhkar with a reader and counter; optional morning, evening, after-prayer, and sleep reminders.",
        ["WizardWelcome"] = "Welcome to SAMT",
        ["OpenGitHub"] = "GitHub",
        ["PublisherLabel"] = "Publisher",
        ["VersionLabel"] = "Version",
        ["CheckForUpdates"] = "Check for updates",
        ["AutoCheckUpdates"] = "Check for updates automatically",
        ["PlaceSearch"] = "Search for a place",
        ["PlaceSearchHint"] = "Search by name (requires Internet). You can refine coordinates manually.",
        ["PlaceSearchNoResults"] = "No results.",
        ["PlaceSearchFailed"] = "Could not search. Check the network or enter coordinates.",
        ["PlaceSearchAttribution"] = "Place search via open data (OpenStreetMap Nominatim).",
        ["ApplyPlaceResult"] = "Use this place",
        ["UpdateCheckFailed"] = "Could not check for updates.",
        ["UpdateUpToDate"] = "You are on the latest version ({0}).",
        ["UpdateAvailableFormat"] = "New version {0} is available (current {1}).",
        ["UpdateHashMismatch"] = "Update file integrity check failed (SHA-256).",
        ["UpdateDownloadPrompt"] = "Download and run the installer?",
        ["UpdateDownloading"] = "Downloading update…",
        ["Adhkar.Sleep"] = "Sleep adhkar",
        ["AdhkarOpenReader"] = "Open reader",
        ["AdhkarPlay"] = "Play (coming soon)",
        ["AdhkarPrev"] = "Previous",
        ["AdhkarNext"] = "Next",
        ["AdhkarProgressFormat"] = "{0} / {1}",
        ["AdhkarRemindersMaster"] = "Enable Adhkar reminders",
        ["AdhkarMorningToggle"] = "Morning Adhkar",
        ["AdhkarEveningToggle"] = "Evening Adhkar",
        ["AdhkarAfterPrayerToggle"] = "After-prayer Adhkar",
        ["AdhkarSleepToggle"] = "Sleep Adhkar",
        ["AdhkarSettingsHint"] = "Enable each type and set its default display time. After-prayer Adhkar fire after every Adhan, with an optional delay in minutes.",
        ["AdhkarDefaultTime"] = "Time",
        ["AdhkarAfterPrayerDelay"] = "After Adhan by",
        ["AdhkarAfterPrayerHint"] = "After every prayer: show After-prayer Adhkar when the Adhan finishes (or after the delay). 0 = immediately after Adhan / when the Adhan overlay closes.",
        ["AdhkarMinutesUnit"] = "min",

        ["Adhkar.Morning.3.Translation"] = "I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.",
        ["Adhkar.Morning.4.Translation"] = "O Allah, by You we enter the morning, by You we enter the evening, by You we live and die, and to You is the resurrection.",
        ["Adhkar.Morning.5.Translation"] = "Glory be to Allah and praise is His.",
        ["Adhkar.Evening.3.Translation"] = "In the name of Allah with whose name nothing on earth or in the heavens can cause harm…",
        ["Adhkar.Evening.4.Translation"] = "O Allah, by You we enter the evening, by You we enter the morning…",
        ["Adhkar.Evening.5.Translation"] = "I seek refuge in the perfect words of Allah from His anger and punishment…",
        ["Adhkar.AfterPrayer.3a.Translation"] = "Glory be to Allah",
        ["Adhkar.AfterPrayer.3b.Translation"] = "Praise be to Allah",
        ["Adhkar.AfterPrayer.3c.Translation"] = "Allah is the Greatest",
        ["Adhkar.AfterPrayer.4.Translation"] = "There is no god but Allah alone, without partner; His is the dominion and His is the praise, and He is over all things competent.",
        ["Adhkar.Sleep.1.Translation"] = "In Your name, O Allah, I die and I live.",
        ["Adhkar.Sleep.2.Translation"] = "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
        ["Adhkar.Sleep.3.Translation"] = "In Your name, my Lord, I lay my side down and by You I raise it…",
        ["Adhkar.Sleep.4.Translation"] = "The Messenger has believed in what was revealed to him from his Lord, and so have the believers… (see a trusted source for the full ayah).",
        ["Adhkar.Sleep.5.Translation"] = "O Allah, I have submitted myself to You and entrusted my affair to You…",
    };
}
