using System.Globalization;
using Samt.Core.Calculation;
using Samt.Core.Domain;
using Samt.Core.Locations;

var root = FindRepoRoot();
var outPath = Path.Combine(root, "testdata", "kennadsa", "kennadsa-baseline-2025-01.csv");
Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);

var engine = new PrayerEngine();
var location = KnownLocations.Kennadsa;
var profile = CalculationMethods.Algeria;
var start = new DateOnly(2025, 1, 1);

await using var writer = new StreamWriter(outPath);
await writer.WriteLineAsync("# SAMT regression baseline — Kennadsa, Algeria method (Fajr 18° / Isha 17°).");
await writer.WriteLineAsync("# Generated by tools/GenerateBaseline from PrayerEngine. Not an official mosque table.");
await writer.WriteLineAsync("# Replace with a local reference table when available (keep the same columns).");
await writer.WriteLineAsync("date,fajr,sunrise,dhuhr,asr,maghrib,isha");

for (var i = 0; i < 31; i++)
{
    var date = start.AddDays(i);
    var schedule = engine.Calculate(date, location, profile);
    static string T(DateTimeOffset t) => t.ToString("HH:mm", CultureInfo.InvariantCulture);
    await writer.WriteLineAsync(
        $"{date:yyyy-MM-dd},{T(schedule.Fajr)},{T(schedule.Sunrise)},{T(schedule.Dhuhr)},{T(schedule.Asr)},{T(schedule.Maghrib)},{T(schedule.Isha)}");
}

Console.WriteLine($"Wrote {outPath}");

// Also print a sample day for manual inspection
var sample = engine.Calculate(new DateOnly(2025, 1, 15), location, profile);
Console.WriteLine($"Sample 2025-01-15 Kennadsa Algeria:");
foreach (var key in PrayerSchedule.CoreDisplayOrder)
{
    if (sample.Times.TryGetValue(key, out var time))
    {
        Console.WriteLine($"  {key,-10} {time:HH:mm:ss zzz}");
    }
}

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "Samt.sln")))
        {
            return dir.FullName;
        }

        dir = dir.Parent;
    }

    return Directory.GetCurrentDirectory();
}
